
    export const convidados = [
        "MAYK JUNIO SOARES RIOS",
        "Gabriella Carolina Lacerda",
        "Maria Eduarda Lacerda Rios",
        "Antônio Lacerda Rios",
        "Carlos Antônio da Silva de Souza",
        "Esther Lorrane de Souza",
        "Bryan Siqueira de Souza",
        "Bernardo Siqueira de Souza",
        "Benício Siqueira de Souza",
        "Lauanda Poliana da mata de Souza",
        "Cleiton costa de Souza",
        "Lilian conceição da mata",
        "Pedro Rangel junior de Souza",
        "Matheus Lincon Silva Amaral",
        "Philip Morais da Costa",
        "Jessica Tayline Morais dos Santos Costa",
        "Maria Flor Morais da Costa",
        "Débora Cristina Xavier de Oliveira",
        "Gabriel Ramos Gonçalves",
        "Ana Luiza Alves",
        "Robert Braga",
        "Fernanda cordeiro Felipe Rodrigues",
        "Gabryel Rodrigues de Paula",
        "Jaor Henrique Martins de Oliveira",
        "Emília Santos Oliveira",
        "Lucas Gomes Salles",
        "Kele Cristina Siqueira",
        "Jarbas Jaques Carvalho II",
        "Ana Clara Siqueira Gomes",
        "Felipe Souza de Carvalho",
        "Felipe Augusto Almeida Santos",
        "Giovanna Guedes",
        "Noah Guedes",
        "Jeferson Silva Souza",
        "Aline Aparecida da Silva",
        "Mairon David Barbosa Silva",
        "Helena Luiza Silva",
        "Beatriz Antônia Silva",
        "Jaqueline Gonçalves da Silva",
        "Fabiano Vitor Santana",
        "Laura Silva Santana",
        "Fernanda de Souza Gonçalves Silva",
        "Alam Jhone da Silva",
        "Luíza Fernanda Gonçalves Silva",
        "Gianni Bellysa Dornelas",
        "Evandro Delypranque Gonçalves",
        "Bárbarah Brandão",
        "Guedes",
        "Hel Brandão",
        "Patricia Herculano Ferreira",
        "Nadir Herculano",
        "Pedro Guilherme Herculano",
        "Raynara Batista Ramillo",
        "Marianne Guedes de Sousa",
        "Eduardo messias",
        "Fabiano Souza",
        "Renato augusto",
        "Gabriel Alves Dias",
        "Fabiano de Souza Alves",
        "Luciana Fabiana Alves Dias",
        "Davi Rosa Dias",
        "Arthur Alves Dias",
        "Dina Flávia de Freitas Moreira",
        "Ana Paula Ferreira Lessa",
        "Antonni Carlos de Freitas Moreira",
        "Marise de Freitas Moreira",
        "Osmar Heleno Moreira",
        "Raquel Matos Martins",
        "Anna Clara Matos Martins",
        "Rosanilda de Matos Martins",
        "Bruno Pereira de Oliveira",
        "Ana Beatriz Augusta Valério",
        "Roger Filipe Matos Martins",
        "Luara da silva Alvarenga",
        "Luthiana Suelen de Araújo",
        "Murillo Monsueto de Araújo",
        "JULIANO MARQUES",
        "Cynthia Marques",
        "Liliane Gonçalves Rios",
        "Yasmim Barboza Rodrigues",
        "Alex Marciel da Silva",
        "Iuri Natan Teles Gonçalves",
        "Jairo Nunes Rezende",
        "Stephanie Stella de Jesus Pereira",
        "Henrique Pereira Rezende",
        "Rogeria Matos Martins",
        "Joyce Rodrigues dos Santos",
        "Lidiane Cristina Silva Lorena Lima",
        "Douglas Lima Daniel",
        "Marcela Lorena Miranda"
    ]
